---
title: "Final porject_title"
author: "Yu-Ting Huang, Jipeng Cheng, Weidi Hou"
date: "5/1/2022"
output: pdf_document
---

# Abstract
summarize your question, your methods, your results, and your main conclusions in a few hundred words or less.

# Introduction
The importance and influence of dating app cannot be ignored in today's society. For example, "The Tinder Swindler" is one of famous movie in 2022, specially,  global views was 45.8 million hours in its first week of release and hit the top 10 in 92 countries in Netflix. Furthermore, the application "Tinder - Dating New People" is super popular in the US and over 55 billion matches made. Of course, except for Tinder, there are so many dating app such as OkCupid, bumble, and Coffee Meets Bagel to name but a few. 

In this study, the data from Lovoo will be analyzed. The purpose of this research is to build the model and point out what profile can acquire more "likes" (called "kiss" on the Lovoo), as a indicator to capture the potential charisma of people. On the other hand, more "likes" means the person may get more matches and more potential encounters. The one things should be noticed is that our data only collect the sample from "female". Therefore, the results will be fitted for female rather than male.

To have more meaningful explanation, this study created an new variable called "conversion rate", which can avoid the problem that the number of liked has highly correlation with the number of clicks (visit times) compared with using $counts\_kisses$ as a dependent variable. Also, this indicator can effectively explain how to obtain more like from other user by other independent variables.


\centering
$Conversion rate = \frac{counts\_kisses}{counts\_profileVisits}$ (1)

\flushleft
# Data Description

The original data comes from "Dating App User Profiles' stats - Lovoo v3" gathered during spring April and May 2015.  IOS version of the Lovoo app was in version 3 at that time. The original data includes 2940 rows and 39 variables, finally, this research left 22 as valuable variables and create 1 new variable. 

The details of each variable presents in the following table.

|Variable   |Description|
|:---   |:----------|
|conversion |Index for converting times of visits to times of likes, as formula (1)|
|counts_kisses   |Number of unique user accounts that "liked" (called "kiss" on the platform) this user account|
|age   |user age|
|counts_details   |The degree of account completion|
|counts_pictures   |Number of pictures on the user's profile|
|counts_profileVisits  |Number of clicks on this user (to see his/her full profile) from other user accounts|
|flirtInterests_chat   |1 if the user indicated being in search for people to chat with|
|flirtInterests_friend   |1 if the user indicated being open to making friends|
|flirtInterests_date  |1 if the user indicated being open to dating people|
|isVip   |1 if the user is VIP (this status came with benefits)|
|isVerified  |Whether the user's account was verified through one of the methods (Facebook, phone number, ...)|
|lang_count   |Number of languages the user knows|
|lang_fr   |1 if the user can speak French|
|lang_en  |1 if the user can speak English|
|lang_de   |1 if the user can speak German|
|lang_it   |1 if the user can speak Italian|
|lang_es   |1 if the user can speak Spanish|
|lang_pt   |1 if the user can speak Portuguese|
|freshman   |1 if the user register no more than one month|
|hasBirthday  |1 if the user has birthday|
|highlighted   |1 if the user's profile is currently highlighted (at fetch time)|

# Methods (Model)
Describe your data set and the methods you will use to analyze it.

# Results
Tables, figures, and text that illustrate your findings. Keep the focus on the numbers here. You will interpret your results in the next section.

# Conclusion
Interpret what you found. What are the main lessons we should take away from your report?

# Appendix
optional. Any details (like extra figures, etc) that didn’t fit in well with the main report, but that you think are important.

1. Tinder, https://tinder.com
2. ‘The Tinder Swindler’ Becomes First Doc To Lead Netflix’s Weekly Film Chart, https://deadline.com/2022/02/the-tinder-swindler-first-doc-lead-netflixs-weekly-film-chart-1234928573/
3. Lovoo, https://about.lovoo.com/en/#app-features





other


The main body of your report (excluding the appendix) should prob- ably have no more than about 4-6 figures and tables. Use those to focus on the most important results. Put the rest in the appendix if you need more. Number all figures and tables and refer to them by number (Fig- ure 2, Table 3, etc) in the text where appropriate. Do not include a figure or table in the report or the appendix if you don’t discuss it in the text.

1. A written project report that describes your question, your data sources, your methodological approach, and your conclusions. This should be prepared in RMarkdown format and compiled to a PDF document that you post on GitHub. Send me both the link and the PDF itself.
2. The data set itself, in .csv format.
3. A link to the raw .Rmd file used to analyze your data and prepare your report. If your analysis and plots are not 100% reproducible, you will not receive a passing grade.

5–10 type-written pages (no more than 15 pages)
